In [2]:
import pandas as pd

In [3]:
df1 = pd.read_csv(r"postAITS.csv")
df2 = pd.read_csv(r"postAITS2.csv")
df3 = pd.read_csv(r"postAITS3.csv")
df4 = pd.read_csv(r"postAITS4.csv")
df5 = pd.read_csv(r"postAITS5.csv")

In [4]:
df = pd.concat([df1,df2,df3,df4,df5]).drop_duplicates()
df

,id,post_pk,caption_text,like_count,taken_at,username,user_pk,quote_count,repost_count,reshare_count,thread_user_pk,caption_text_translated,sentiment_score,sentiment_label
0,3558787428782179764_187264532,3.558787e+18,Behind the scenes,0.0,2025-02-02 01:42:22,mlssfshn,187264532,0.0,0.0,0.0,6.331078e+10,Behind the scenes,0.997783,POSITIVE
1,3557970465522674878_187264532,3.557970e+18,A little over 24 hours left to vote.\n\n,0.0,2025-01-31 22:39:13,mlssfshn,187264532,0.0,0.0,0.0,6.331078e+10,A little over 24 hours left to vote.,0.969585,NEGATIVE
2,3557782854629238181_187264532,3.557783e+18,"Galaxy Quest \nLots of cutting holes, playing ...",1.0,2025-01-31 16:26:30,mlssfshn,187264532,0.0,0.0,0.0,6.331078e+10,"Galaxy Quest \nLots of cutting holes, playing ...",0.868657,NEGATIVE
3,3557776470965660229_187264532,3.557776e+18,Black Hole Sun\nOver 5 pounds of cornhusk in m...,0.0,2025-01-31 16:13:49,mlssfshn,187264532,0.0,0.0,0.0,6.331078e+10,Black Hole Sun\nOver 5 pounds of cornhusk in m...,0.935727,NEGATIVE
4,3556000079513982405_187264532,3.556000e+18,Over due to post videos of my work for @salina...,0.0,2025-01-29 05:24:26,mlssfshn,187264532,0.0,0.0,0.0,6.331078e+10,Over due to post videos of my work for @salina...,0.998091,NEGATIVE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133302,3575014769692682879_62270892756,3.575015e+18,NaN,1.0,1740394992,bharatparsadachary,62270892756,0.0,1.0,NaN,6.414787e+10,NaN,NaN,NaN
133303,3574960067294644779_62270892756,3.574960e+18,NaN,1.0,1740388471,bharatparsadachary,62270892756,0.0,2.0,NaN,6.414787e+10,NaN,NaN,NaN
133304,3574959296431870237_62270892756,3.574959e+18,NaN,1.0,1740388379,bharatparsadachary,62270892756,0.0,1.0,NaN,6.414787e+10,NaN,NaN,NaN
133305,3574957613710801225_62270892756,3.574958e+18,NaN,1.0,1740388179,bharatparsadachary,62270892756,0.0,1.0,NaN,6.414787e+10,NaN,NaN,NaN
133306,3574956079400856243_62270892756,3.574956e+18,NaN,1.0,1740387996,bharatparsadachary,62270892756,0.0,1.0,NaN,6.414787e+10,NaN,NaN,NaN